#!/bin/sh
. /usr/lib/libath9k-wathdog

# CD to avoid annoying prefixes
cd $WD_QUEUE_DIR

#Poll directory every 10 secs
while [ 1 = 1 ]
do
	for f in $(ls .); do 
		local upload_ret_code = $(upload_compressed_query_string $f)
		if [ $upload_ret_code -qe 0 ]; then # 
			rm $f
		fi
	done
	sleep 10
done
