#!/bin/sh
logread -f | while read line
do
	case "$line" in
	*"phy0: Could not stop RX"*)
	echo "Processing $line"
                date >> /tmp/test.log
                wifi reset
		;;
	*)
		 echo "No Match: $line"
		;;
	esac
done
