#!/bin/sh
logread -f | while read line
do
	case "$line" in
	*ResetWLAN*) 
	echo "Processing $line"
            /usr/bin/ath9k-watchdog-postmortem &
   			sleep 2 #Post-mortem will have 2 seks for saving logs, before we pollute 'em
			wifi reset
		;;
	*)
		 echo "No Match: $line"
		;;
	esac
done
